### ISSUE TITLE
The image is loaded transposed with `pyheif==0.8.0`

### ISSUE THREAD

**Issue by vanaoff** [uploadcare/heif-image-plugin#27]
### Describe the bug

The `PIL.Image` is loaded transposed with `pyheif==0.8.0`.

### Expected behavior
The image is loaded in original shape.

### Code

```
import HeifImagePlugin 
import pyheif
from PIL import Image

image = pyheif.open("example.heif")
print(image.size)
# (3024, 4032)

image_pil = Image.open("example.heif")
print(image_pil.size)
# (4032, 3024)
```
[example.heif.zip](https://github.com/user-attachments/files/16905176/example.heif.zip)

### Environment

 - Library version: 0.6.2
 - Language/framework version: Python 3.11.9
 - OS version: Linux

**Comment by homm** [comment]
> The image is loaded transposed

This is the desired behavior since the image bitmap in the file is actually rotated, and the correct orientation is stored in the EXIF data. You should use the `PIL.ImageOps.exif_transpose()` function to restore the orientation.

This decision was made because the built-in libheif transposition is several times slower than the highly optimized, CPU cache-friendly implementation in Pillow. This improves image loading time [up to 60%](https://github.com/strukturag/libheif/pull/555).

**Comment by homm** [comment]
Updated [README](https://github.com/uploadcare/heif-image-plugin?tab=readme-ov-file#how-to-use).

**Comment by vanaoff** [comment]
Thanks :blush:
